User Settings page
lattln/EHR-Dashboard pull request #6
Opened 2024-12-05 16:11 UTC by CollinFoord

Added the User Settings page to the EHR Dashboard.

2024-12-05 16:29 UTC, jengledow commented on imports/ui/pages/UserSettings.jsx
I feel like to keep everything in line using the daisyui button and input components would be good - just as easy as adding the 'btn' and 'input' class to the respective elements

https://daisyui.com/components/input/

2024-12-05 16:33 UTC, jengledow reviewed
i put a comment on the jsx about using the daisyui components so that way it matches with the rest of the app

2024-12-05 23:59 UTC, lattln requested changes
![image](https://github.com/user-attachments/assets/e29bf7e4-8031-4b68-9d59-047545f8b8e2)

Make sure to use the constants inside of ui/constants/dashboard.js
![image](https://github.com/user-attachments/assets/3f80bf6e-e996-483b-8759-0467e82ebee0)

And UserSetting,jsx should be inside of ui/components/Dashboard inside of pages. Since it is a component of the "Dashboard" Page.

Looks good otherwise.

2024-12-06 02:38 UTC, jengledow approved these changes
besides what lin said the changes look good

2024-12-09 20:43 UTC, lattln commented
```javascript 


export const USER_INFO = {
    name: {
        label: "Name",
        firstName_value: "John"
        lastName_value: "Smith"
    },
    gender: {
        label: "Gender",
        value: "Male",
    },
    birth: {
        label: "Birthday",
        value: "3/12/1987",
    },
    physician: {
        label: "Physician",
        value: "Dr. Dre",
    },
    lastAppt: {
        label: "Last Appointment",
        value: "10/18/2024",
    },
};


//EXAMPLE USAGE

<input
   type="text"
   id="firstName"
   name="firstName"
   value={USER_INFO.name.firstName_value}
   onChange={handleChange}
   className="input input-bordered w-full"
/>
```

2024-12-09 21:48 UTC, lattln approved these changes
lgtm

2024-12-09 22:26 UTC, merged